"""
Web search tool for retrieving recent information.

This tool uses DuckDuckGo Search (DDGS) to perform
real-time web searches.
"""

from ddgs import DDGS
from langchain_core.tools import tool

from app.utils.logger import get_logger

logger = get_logger(__name__)

# Shared DDGS client
ddgs = DDGS()


def _search_and_validate(query: str) -> list[dict]:
    """
    Execute a DDGS search, validate results, rank them,
    and return the strongest recent sources.
    """

    results = ddgs.text(
        query,
        max_results=10,
    )

    if results is None:
        logger.warning(
            "search_web | Search provider returned no response"
        )
        return []

    valid_results = []

    for result in results:
        if not isinstance(result, dict):
            continue

        title = result.get("title")
        body = result.get("body", "")
        href = result.get("href")
        date = result.get("date", "")

        if not title or not href:
            logger.warning(
                "search_web | Skipping result without title or href"
            )
            continue

        valid_results.append(
            {
                "title": title,
                "body": body or "",
                "href": href,
                "date": date or "",
            }
        )

    logger.info(
        f"search_web | DDGS returned "
        f"{len(valid_results)} valid candidates"
    )

    # -------------------------------------------------
    # Rank candidates by research usefulness
    # -------------------------------------------------

    def score_result(result: dict) -> int:
        title = result["title"].lower()
        body = result["body"].lower()
        href = result["href"].lower()
        date = result.get("date", "").lower()

        text = f"{title} {body}"

        score = 0

        # Prefer official company sources.
        if "microsoft.com" in href:
            score += 5

        if "blogs.microsoft.com" in href:
            score += 3

        if "news.microsoft.com" in href:
            score += 3

        if "azure.microsoft.com" in href:
            score += 3

        # Prefer AI/ML/engineering/research relevance.
        relevant_terms = [
            "artificial intelligence",
            "ai",
            "machine learning",
            "research",
            "engineering",
            "infrastructure",
            "copilot",
            "azure",
            "agentic",
            "scientific",
            "technology",
        ]

        for term in relevant_terms:
            if term in text:
                score += 1

        # Prefer explicitly recent results.
        recent_terms = [
            "2026",
            "today",
            "hours ago",
            "days ago",
            "weeks ago",
            "month ago",
        ]

        for term in recent_terms:
            if term in text or term in date:
                score += 3

        # Penalize generic/reference content.
        low_value_terms = [
            "wikipedia",
            "company overview",
            "history",
            "stock",
            "market",
            "share price",
        ]

        for term in low_value_terms:
            if term in text:
                score -= 4

        result["_score"] = score

        return score

    for result in valid_results:
        score_result(result)

    valid_results.sort(
        key=lambda result: result["_score"],
        reverse=True,
    )

    # Keep only the strongest research sources.
    top_results = valid_results[:5]

    for index, result in enumerate(top_results, start=1):
        logger.info(
            f"search_web | Selected {index}: "
            f"{result['title']} | score={result['_score']}"
        )

    # Remove internal scoring metadata before returning.
    for result in top_results:
        result.pop("_score", None)

    return top_results


@tool
def search_web(query: str) -> list[dict]:
    """
    Search the web for recent information.

    Performs a focused search first. If no valid results
    are found, falls back to a broader search query.
    """
    
    try:
        # -------------------------------------------------
        # Attempt 1: focused query generated by the agent
        # -------------------------------------------------

        logger.info(
            f"search_web | Primary search: {query}"
        )

        valid_results = _search_and_validate(query)

        if valid_results:
            logger.info(
                f"search_web | Retrieved "
                f"{len(valid_results)} valid results"
            )

            return valid_results

        logger.warning(
            "search_web | Primary search returned no "
            "valid results. Trying fallback search."
        )

        # -------------------------------------------------
        # Attempt 2: broader fallback search
        # -------------------------------------------------

        fallback_query = (
            f"{query.replace('site:', '')} "
            f"latest news 2026"
        )

        logger.info(
            f"search_web | Fallback search: {fallback_query}"
        )

        valid_results = _search_and_validate(
            fallback_query
        )

        logger.info(
            f"search_web | Fallback retrieved "
            f"{len(valid_results)} valid results"
        )

        return valid_results

    except Exception as e:
        logger.error(
            f"search_web | Search failed: {e}"
        )

        raise RuntimeError(
            "Web search failed. The search service may be temporarily unavailable."
        ) from e