"""
Web search tool for retrieving recent information.

This tool uses DuckDuckGo Search (DDGS) to perform
real-time web searches.
"""

from ddgs import DDGS
from langchain_core.tools import tool

from app.utils.logger import get_logger

logger = get_logger(__name__)

# Shared DDGS client
ddgs = DDGS()


def _search_and_validate(query: str) -> list[dict]:
    """
    Execute a DDGS search and return only valid results.
    """

    results = ddgs.text(
        query,
        max_results=5,
    )

    valid_results = []

    for result in results:
        if not isinstance(result, dict):
            continue

        title = result.get("title")
        body = result.get("body", "")
        href = result.get("href")

        # A result needs a title and source URL.
        # Body text is optional.
        if not title or not href:
            logger.warning(
                "search_web | Skipping result without title or href"
            )
            continue

        valid_results.append(
            {
                "title": title,
                "body": body or "",
                "href": href,
            }
        )

    return valid_results


@tool
def search_web(query: str) -> list[dict]:
    """
    Search the web for recent information.

    Performs a focused search first. If no valid results
    are found, falls back to a broader search query.
    """

    try:
        # -------------------------------------------------
        # Attempt 1: focused query generated by the agent
        # -------------------------------------------------

        logger.info(
            f"search_web | Primary search: {query}"
        )

        valid_results = _search_and_validate(query)

        if valid_results:
            logger.info(
                f"search_web | Retrieved "
                f"{len(valid_results)} valid results"
            )

            return valid_results

        logger.warning(
            "search_web | Primary search returned no "
            "valid results. Trying fallback search."
        )

        # -------------------------------------------------
        # Attempt 2: broader fallback search
        # -------------------------------------------------

        fallback_query = (
            f"{query.replace('site:', '')} "
            f"latest news 2026"
        )

        logger.info(
            f"search_web | Fallback search: {fallback_query}"
        )

        valid_results = _search_and_validate(
            fallback_query
        )

        logger.info(
            f"search_web | Fallback retrieved "
            f"{len(valid_results)} valid results"
        )

        return valid_results

    except Exception as e:
        logger.error(
            f"search_web | Search failed: {e}"
        )

        return []